"""Initial database schema with UUID primary keys

Revision ID: 251d1db8a18d
Revises: 
Create Date: 2026-02-16 16:13:13.993002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = '251d1db8a18d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_pin_hash', sa.String(length=128), nullable=False),
    sa.Column('pin_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.DateTime(), nullable=True),
    sa.Column('parent_email', sa.String(length=254), nullable=True),
    sa.Column('consent_code_hash', sa.String(length=64), nullable=True),
    sa.Column('consent_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('has_minor_users', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_api_token_hash'), 'families', ['api_token_hash'], unique=True)
    op.create_table('recipes',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=2), nullable=False),
    sa.Column('why', sa.String(length=500), nullable=True),
    sa.Column('tip', sa.String(length=500), nullable=True),
    sa.Column('serves', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('version_added', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_category'), 'recipes', ['category'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_weather'), 'recipes', ['weather'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('family_id', GUID(length=36), nullable=True),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', GUID(length=36), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_family_id', 'audit_log', ['family_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('recipe_id', GUID(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('ingredient_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_ingredients_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_steps',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('recipe_id', GUID(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_steps_recipe_id', 'recipe_steps', ['recipe_id'], unique=False)
    op.create_table('recipe_tags',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('recipe_id', GUID(length=36), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_tags_tag'), 'recipe_tags', ['tag'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('family_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_family_id', 'users', ['family_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('recipe_id', GUID(length=36), nullable=False),
    sa.Column('favorited_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_favorites', 'user_favorites', ['user_id', 'recipe_id'], unique=True)
    op.create_table('user_ingredients',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_ingredients', 'user_ingredients', ['user_id', 'tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_ingredients', table_name='user_ingredients')
    op.drop_table('user_ingredients')
    op.drop_index('ix_user_favorites', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index('ix_users_family_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipe_tags_tag'), table_name='recipe_tags')
    op.drop_table('recipe_tags')
    op.drop_index('ix_recipe_steps_recipe_id', table_name='recipe_steps')
    op.drop_table('recipe_steps')
    op.drop_index('ix_recipe_ingredients_recipe_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_audit_log_family_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_recipes_weather'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_category'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_families_api_token_hash'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
